from __future__ import annotations

import ipaddress
import threading
import time
from collections import deque
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Deque, Dict, Optional, Tuple

from flask import Flask, Response, g, jsonify, request


_RATE_WINDOW_SECONDS = 10.0
_EXCLUDED_PATHS = {"/api/v1/traffic"}


@dataclass
class RequestMeasurement:
    upload_bytes: int
    page_view: bool
    remote: bool
    finished: bool = False


def _header_size(headers: Any) -> int:
    try:
        return sum(len(str(key).encode("utf-8")) + len(str(value).encode("utf-8")) + 4 for key, value in headers)
    except (TypeError, ValueError):
        return 0


def _is_remote_address(value: Optional[str]) -> bool:
    try:
        return not ipaddress.ip_address(value or "").is_loopback
    except ValueError:
        return bool(value)


class TrafficMeter:
    """Low-overhead HTTP application-layer traffic counters.

    Upload is request data received from WebUI clients. Download is response
    data sent back to them. Values include an estimate of HTTP headers and do
    not contain hotel-provider traffic generated by the scan engine.
    """

    def __init__(self, clock=time.monotonic) -> None:
        self._clock = clock
        self._started_at = self._clock()
        self._started_wall = datetime.now(timezone.utc).isoformat(timespec="seconds")
        self._lock = threading.Lock()
        self._requests = 0
        self._page_views = 0
        self._remote_requests = 0
        self._failed_requests = 0
        self._upload_bytes = 0
        self._download_bytes = 0
        self._active_requests = 0
        self._last_request_at = ""
        self._recent: Deque[Tuple[float, int, int]] = deque()

    def begin(
        self,
        *,
        method: str,
        path: str,
        query_string: bytes = b"",
        content_length: Optional[int] = None,
        headers: Any = (),
        remote_addr: Optional[str] = None,
    ) -> Optional[RequestMeasurement]:
        if path in _EXCLUDED_PATHS:
            return None
        request_line = f"{method} {path}".encode("utf-8")
        upload_bytes = len(request_line) + len(query_string or b"") + 12
        upload_bytes += max(0, int(content_length or 0)) + _header_size(headers)
        measurement = RequestMeasurement(
            upload_bytes=upload_bytes,
            page_view=method.upper() == "GET" and path == "/",
            remote=_is_remote_address(remote_addr),
        )
        with self._lock:
            self._active_requests += 1
        return measurement

    def finish(
        self,
        measurement: Optional[RequestMeasurement],
        *,
        status_code: int,
        content_length: Optional[int] = None,
        headers: Any = (),
    ) -> None:
        if measurement is None or measurement.finished:
            return
        response_bytes = max(0, int(content_length or 0)) + _header_size(headers) + 16
        now = self._clock()
        measurement.finished = True
        with self._lock:
            self._requests += 1
            self._page_views += int(measurement.page_view)
            self._remote_requests += int(measurement.remote)
            self._failed_requests += int(int(status_code) >= 400)
            self._upload_bytes += measurement.upload_bytes
            self._download_bytes += response_bytes
            self._active_requests = max(0, self._active_requests - 1)
            self._last_request_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
            self._recent.append((now, measurement.upload_bytes, response_bytes))
            self._trim_recent(now)

    def abort(self, measurement: Optional[RequestMeasurement]) -> None:
        if measurement is None or measurement.finished:
            return
        measurement.finished = True
        with self._lock:
            self._active_requests = max(0, self._active_requests - 1)

    def _trim_recent(self, now: float) -> None:
        threshold = now - _RATE_WINDOW_SECONDS
        while self._recent and self._recent[0][0] < threshold:
            self._recent.popleft()

    def snapshot(self) -> Dict[str, Any]:
        now = self._clock()
        with self._lock:
            self._trim_recent(now)
            upload_recent = sum(item[1] for item in self._recent)
            download_recent = sum(item[2] for item in self._recent)
            if self._recent:
                observed = max(1.0, min(_RATE_WINDOW_SECONDS, now - self._recent[0][0] + 1.0))
            else:
                observed = _RATE_WINDOW_SECONDS
            return {
                "started_at": self._started_wall,
                "uptime_sec": max(0, int(now - self._started_at)),
                "requests": self._requests,
                "page_views": self._page_views,
                "remote_requests": self._remote_requests,
                "failed_requests": self._failed_requests,
                "active_requests": self._active_requests,
                "upload_bytes": self._upload_bytes,
                "download_bytes": self._download_bytes,
                "upload_bps": round(upload_recent / observed, 1),
                "download_bps": round(download_recent / observed, 1),
                "rate_window_sec": int(_RATE_WINDOW_SECONDS),
                "last_request_at": self._last_request_at,
                "scope": "webui_http_estimate",
            }


meter = TrafficMeter()


def _response_content_length(response: Response) -> int:
    value = response.content_length
    if value is not None:
        return max(0, int(value))
    try:
        value = response.calculate_content_length()
    except (RuntimeError, TypeError, ValueError):
        value = None
    return max(0, int(value or 0))


def configure_traffic_meter(app: Flask, traffic_meter: TrafficMeter = meter) -> None:
    @app.before_request
    def _traffic_begin() -> None:
        g.toyoko_traffic_measurement = traffic_meter.begin(
            method=request.method,
            path=request.path,
            query_string=request.query_string,
            content_length=request.content_length,
            headers=request.headers,
            remote_addr=request.remote_addr,
        )

    @app.after_request
    def _traffic_finish(response: Response) -> Response:
        traffic_meter.finish(
            getattr(g, "toyoko_traffic_measurement", None),
            status_code=response.status_code,
            content_length=_response_content_length(response),
            headers=response.headers,
        )
        return response

    @app.teardown_request
    def _traffic_abort(_error: Optional[BaseException]) -> None:
        traffic_meter.abort(getattr(g, "toyoko_traffic_measurement", None))


def traffic_snapshot() -> Dict[str, Any]:
    return meter.snapshot()


def traffic_snapshot_response() -> Response:
    return jsonify({"ok": True, "traffic": traffic_snapshot()})
